#!/bin/bash

#generate key and certificate
openssl req -x509 -nodes -days {{ssl_valid_days}} -newkey rsa:2048 -keyout /sslnginx/keys/selfsigned.key -out /sslnginx/keys/selfsigned.crt -subj "/C=US/ST={{ssl_state}}/L={{ssl_city}}/O={{ssl_organization}}/CN={{nginx_server_name}}"

#generate dhparam
openssl dhparam -out /sslnginx/keys/dhparam.pem 2048
